- id: talonfmt
  name: talonfmt
  description: "talonfmt: .talon file formatter"
  entry: talonfmt
  args: [--fail-on-change]
  types: [file]
  files: \.talon$
  language: python
  language_version: python3.10
