- id: talonfmt
  name: talonfmt
  description: "talonfmt: .talon file formatter"
  entry: talonfmt
  args: ["--in-place", "--quiet"]
  types: [file]
  files: \.talon$
  language: python
  language_version: python3.10
