name: release

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: Setup requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-ci.txt

      - name: Build Package
        run: |
          pipx run --spec poetry==1.4.0 \
            poetry build

      # - name: Publish to PyPi
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     verbose: true
      #     password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**.tar.gz
            dist/**.whl
          fail_on_unmatched_files: true
